export const propertyCodeClasses = {
    100: 'Land',
    200: 'Farm',
    300: 'Residential',
    400: 'Commercial',
    500: 'Industrial',
    600: 'Institutional',
    700: 'Special Purpose',
    800: 'Government'
};
export const propertyCodeNames = {
    100: 'Vacant residential land not on water',
    101: 'Second tier vacant lot',
    102: 'Conservation Authority land',
    103: 'Municipal park',
    105: 'Vacant commercial land',
    106: 'Vacant industrial land',
    107: 'Provincial park',
    108: 'Federal park',
    109: 'Large land holdings, greater than 1000 acres',
    110: 'Vacant residential/recreational land on water',
    111: 'Island under single ownership',
    112: 'Multi-residential vacant land',
    113: 'Condominium development land - residential (vacant lot)',
    114: 'Condominium development land - non residential (vacant lot)',
    115: 'Property in process of redevelopment utilizing existing structure(s)',
    120: 'Water lot (entirely under water)',
    125: 'Residential development land',
    127: 'Townhouse block - freehold units',
    130: 'Non-buildable land',
    134: 'Land designated and zoned for open space',
    140: 'Common land',
    150: 'Mining lands - patented',
    151: 'Mining lands - unpatented',
    155: 'Land associated with power dam',
    169: 'Vacant land condominium (residential)',
    200: 'Farm property without any buildings/structures',
    201: 'Farm with residence - with or without secondary structures; no farm outbuildings',
    210: 'Farm without residence - with secondary structures; with farm outbuildings',
    211: 'Farm with residence - with or without secondary structures; with farm outbuildings',
    220: 'Farm without residence - with commercial/industrial operation',
    221: 'Farm with residence - with commercial/industrial operation',
    222: 'Farm with a winery',
    223: 'Grain/seed and feed operation',
    224: 'Tobacco farm',
    225: 'Ginseng farm',
    226: 'Exotic farms',
    227: 'Nut Orchard',
    228: 'Farm with gravel pit',
    229: 'Farm with campground/mobile home park',
    230: 'Intensive farm operation - without residence',
    231: 'Intensive farm operation - with residence',
    232: 'Large scale greenhouse operation',
    233: 'Large scale swine operation',
    234: 'Large scale poultry operation',
    235: 'Government - agriculture research facility',
    236: 'Farm with oil/gas well(s)',
    240: 'Managed forest property, vacant land not on water',
    241: 'Managed forest property, vacant land on water',
    242: 'Managed forest property, seasonal residence not on water',
    243: 'Managed forest property, seasonal residence on water',
    244: 'Managed forest property, residence not on water',
    245: 'Managed forest property, residence on water',
    260: 'Vacant residential/commercial/ industrial land owned by a non-farmer with a portion being farmed',
    261: 'Land owned by a non-farmer improved with a non-farm residence with a portion being farmed',
    262: 'Land owned by a farmer improved with a non-farm residence with a portion being farmed',
    301: 'Single family detached (not on water)',
    302: 'More than one structure used for residential purposes',
    303: 'Residence with a commercial unit',
    304: 'Residence with a commercial/ industrial use building',
    305: 'Link home',
    306: 'Boathouse with residence above',
    307: 'Community lifestyle (not a mobile home park)',
    309: 'Freehold Townhouse/Row house',
    311: 'Semi-detached residential',
    313: 'Single family detached on water',
    314: 'Clergy Residence',
    322: 'Semi-detached residence with both units under one ownership',
    332: 'Residential structure with two self-contained units.',
    333: 'Residential property with three self-contained units',
    334: 'Residential property with four self-contained units',
    335: 'Residential property with five self-contained units',
    336: 'Residential property with six self-contained units',
    340: 'Multi-residential, with 7 or more self-contained units',
    341: 'Multi-residential, with 7 or more self-contained residential units, with small commercial unit(s)',
    350: 'Row housing, with three to six units under single ownership',
    352: 'Row housing, with seven or more units under single ownership',
    360: 'Rooming or boarding house',
    361: 'Bachelorette',
    363: 'House-keeping cottages - no American plan',
    364: 'House-keeping cottages - less than 50% American plan',
    365: 'Group Home',
    366: 'Student housing (off campus)',
    367: 'Service or amenity unit',
    368: 'Residential Dockominium',
    369: 'Vacant land condominium (residential - improved)',
    370: 'Residential Condominium Unit',
    371: 'Life Lease - No Redemption.',
    372: 'Life Lease - Return on Invest.',
    373: 'Cooperative housing – equity',
    374: 'Cooperative housing - non-equity',
    375: 'Co-ownership',
    376: 'Condominium locker unit – separately deeded.',
    377: 'Condominium parking space/unit – separately deeded.',
    378: 'Residential Leasehold Condominium Corporation',
    379: 'Residential phased condominium corporation',
    380: 'Residential common elements condominium corporation',
    381: 'Mobile home',
    382: 'Mobile home park',
    383: 'Bed and breakfast establishment',
    385: 'Time-share, fee simple',
    386: 'Time share, right-to-use',
    391: 'Seasonal/recreational dwelling - first tier on water',
    392: 'Seasonal/recreational dwelling - second tier to water',
    395: 'Seasonal/recreational dwelling - not located on water',
    400: 'Small Office building',
    401: 'Small Medical/dental building',
    402: 'Large office building',
    403: 'Large medical/dental building',
    405: 'Office use converted from house',
    406: 'Retail use converted from house',
    407: 'Retail lumber yard',
    408: 'Freestanding Beer Store or LCBO',
    409: 'Retail',
    410: 'Retail',
    411: 'Restaurant - conventional',
    412: 'Restaurant - fast food',
    413: 'Restaurant - conventional, national chain',
    414: 'Restaurant - fast food, national chain',
    415: 'Cinema/movie house/drive-in',
    416: 'Concert hall/live theatre',
    417: 'Entertainment complex',
    419: 'Automotive service centre, highway - 400 series highways',
    420: 'Automotive fuel station with or without service facilities',
    421: 'Specialty automotive shop',
    422: 'Auto dealership',
    423: 'Auto dealership',
    425: 'Neighbourhood shopping centre',
    426: 'Small box shopping centre',
    427: 'Big box shopping/power centre',
    428: 'Regional shopping centre',
    429: 'Community shopping centre',
    430: 'Neighbourhood shopping centre',
    431: 'Department store',
    432: 'Banks and similar financial institutions, including credit unions',
    433: 'Banks and similar financial institutions, including credit unions',
    434: 'Freestanding supermarket',
    435: 'Large retail building centre',
    436: 'Freestanding large retail store, national chain',
    438: 'Neighbourhood shopping centre with offices above',
    441: 'Tavern/public house/small hotel',
    444: 'Full service hotel',
    445: 'Limited service hotel',
    446: 'Apartment hotel',
    447: 'Condominium Hotel Unit',
    450: 'Motel',
    451: 'Seasonal motel',
    460: 'Resort hotel',
    461: 'Resort lodge',
    462: 'Country inns & small inns',
    463: 'Fishing/hunting lodges/resorts',
    465: 'Child and community oriented camp/resort',
    470: 'Multi-type complex',
    471: 'Retail or office with residential unit(s) above or behind',
    472: 'Retail or office with residential unit(s) above or behind',
    473: 'Retail with more than one non-retail use',
    475: 'Commercial condominium',
    476: 'Commercial condominium (live/work)',
    477: 'Retail with office(s)',
    478: 'Retail with office(s)',
    480: 'Surface parking lot',
    481: 'Parking garage',
    482: 'Surface parking lot',
    483: 'Parking garage',
    486: 'Campground',
    487: 'Billboard',
    489: 'Driving range/golf centre',
    490: 'Golf course',
    491: 'Ski resort',
    492: 'Marina - located on waterfront',
    493: 'Marina - not located on waterfront',
    495: 'Communication towers',
    496: 'Communication buildings',
    500: 'Mines - active',
    501: 'Mines - inactive',
    502: 'Mine tailings site associated with an active mine',
    503: 'Mine tailings site not associated with an active mine',
    504: 'Oil/gas wells',
    505: 'Sawmill/lumber mill',
    506: 'Forest products',
    510: 'Heavy manufacturing (non-automotive)',
    511: 'Pulp and paper mill',
    512: 'Cement/asphalt manufacturing plant',
    513: 'Steel mill',
    514: 'Automotive assembly plant',
    515: 'Shipyard/dry-dock',
    516: 'Automotive parts production plant',
    517: 'Specialty steel production (mini-mills)',
    518: 'Smelter/ore processing',
    519: 'Foundry',
    520: 'Standard industrial properties not specifically identified by other industrial Property Codes',
    521: 'Distillery/brewery',
    522: 'Grain elevators - Great Lakes waterway',
    523: 'Grain handling - Primary elevators (including feed mills)',
    525: 'Process elevators - flour mills, oilseed crushing, malt houses',
    527: 'Abattoir/slaughter house/rendering plants',
    528: 'Food processing plant',
    529: 'Freezer plant/cold storage',
    530: 'Warehousing',
    531: 'Mini-warehousing',
    532: 'Dry Cleaning Plant',
    535: 'Research and development facilities',
    540: 'Other industrial',
    541: 'Printing plant',
    544: 'Truck terminal',
    545: 'Major distribution centre',
    550: 'Petro-chemical plant',
    551: 'Oil refinery',
    552: 'Tank farm',
    553: 'Bulk oil/fuel distribution terminal',
    555: 'O.P.G. Hydraulic Generating Station',
    556: 'O.P.G. Nuclear Generating Station',
    557: 'O.P.G. Fossil Generating Station',
    558: 'Hydro One Transformer Station',
    559: 'MEU Generating Station',
    560: 'MEU Transformer Station',
    561: 'Hydro One Right-of-Way',
    562: 'Private Hydro Rights-of-Way',
    563: 'Private Hydraulic Generating Station',
    564: 'Private Nuclear Generating Station',
    565: 'Private Generating Station (Fossil Fuels and Cogen)',
    566: 'Private Transformer Station',
    567: 'Wind Turbine',
    568: 'Solar/Photo Voltaic Electricity Generating Facility',
    575: 'Industrial condominium',
    580: 'Industrial mall',
    588: 'Pipelines',
    589: 'Compressor station',
    590: 'Water treatment/filtration/water towers/pumping station',
    591: 'Sewage treatment/waste pumping/waste disposal',
    592: 'Dump/transfer station/incineration plant/landfill',
    593: 'Gravel pit, quarry, sand pit',
    594: 'Peat moss operation',
    595: 'Heat or steam plant',
    596: 'Recycling facility',
    597: 'Railway right-of-way',
    598: 'Railway buildings and lands described as assessable in the Assessment Act',
    599: 'GO transit station/rail yard',
    601: 'Post secondary education',
    602: 'Multiple occupancy educational institutional residence located on or off campus',
    605: 'School',
    608: 'Day Care',
    610: 'Other educational institution',
    611: 'Other institutional residence',
    621: 'Hospital, private or public',
    623: 'Continuum of care seniors facility',
    624: 'Retirement/nursing home (combined)',
    625: 'Nursing home',
    626: 'Old age/retirement home',
    627: 'Other health care facility',
    630: 'Federal penitentiary or correctional facility',
    631: 'Provincial correctional facility',
    632: 'Other correctional facility',
    700: 'Place of worship - with a clergy residence',
    701: 'Place of Worship - without a clergy residence',
    702: 'Cemetery',
    703: 'Cemetery with non-internment services',
    704: 'Crematorium',
    705: 'Funeral Home',
    710: 'Recreational sport club - non commercial',
    711: 'Bowling alley',
    713: 'Casino',
    715: 'Racetrack - auto',
    716: 'Racetrack - horse, with slot facility',
    717: 'Racetrack - horse, without slot facility',
    718: 'Exhibition grounds/fair grounds',
    720: 'Commercial sport complex',
    721: 'Non-commercial sports complex',
    722: 'Professional sports complex',
    725: 'Amusement park',
    726: 'Amusement park - large/regional',
    730: 'Museum and/or art gallery',
    731: 'Library and/or literary institutions',
    733: 'Convention, conference, congress centre',
    734: 'Banquet hall',
    735: 'Assembly hall, community hall',
    736: 'Clubs - private, fraternal',
    737: 'Federal airport',
    738: 'Provincial airport',
    739: 'Local government airport',
    740: 'Airport leasehold',
    741: 'Airport Authority',
    742: 'Public transportation - easements and rights',
    743: 'International bridge/tunnel',
    744: 'Private airport/hangar',
    745: 'Recreational airport',
    746: 'Subway station',
    748: 'Transit garage',
    749: 'Public transportation - other',
    750: 'Scientific, pharmaceutical, medical research facility (structures predominantly other than office)',
    755: 'Lighthouses',
    760: 'Military base or camp (CFB)',
    761: 'Armoury',
    762: 'Military education facility',
    805: 'Post office or depot',
    806: 'Postal mechanical sorting facility',
    810: 'Fire Hall',
    812: 'Ambulance Station',
    815: 'Police Station',
    822: 'Government - agricultural research facility',
    824: 'Government - wharves and harbours',
    826: 'Government - special educational facility',
    828: 'Government - canals and locks',
    830: 'Government - navigational facilities',
    832: 'Government - historic site or monument',
    840: 'Port authority - port activities',
    842: 'Port authority - other activities'
};
export const serviceCodeNames = {
    A: 'All Services',
    H: 'Hydro Access',
    M: 'Municipal Water',
    N: 'No Services',
    P: 'Part Services',
    S: 'Sanitary Services',
    T: 'Septic System',
    W: 'Well Water',
    X: 'No Water',
    Y: 'No Water Disposal'
};
export const accessCodeNames = {
    Y: 'Year Round Access by Road',
    I: 'Island Access',
    L: 'Land Locked',
    N: 'No Road Access',
    O: 'Private Road Access',
    R: 'Right-of-Way Access',
    S: 'Summer or Seasonal Access Only',
    W: 'Water Access Only'
};
export const characterOfConstructionDescriptions = {
    A: {
        framing: 'Structural steel columns and beams fireproofed with masonry, concrete, plaster or other incombustible material',
        floor: 'Concrete or concrete covered steel deck, fireproofed',
        roof: 'Formed concrete, precast slabs, concrete or gypsum on steel deck, fireproofed',
        walls: 'Non-bearing cavity or curtain walls, masonry, concrete, metal panels, stone'
    },
    B: {
        framing: 'Reinforced concrete columns and beams',
        floor: 'Concrete or concrete covered steel deck, fireproofed',
        roof: 'Formed concrete, precast slabs, concrete or gypsum on steel deck, fireproofed',
        walls: 'Non-bearing cavity or curtain walls, masonry, concrete, metal panels, stone'
    },
    C: {
        framing: 'Masonry or concrete load-bearing walls with or without plasters or non load-bearing walls with concrete, wood or steel supporting the load',
        floor: 'Wood or steel floor joists or slab on ground',
        roof: 'Wood or steel joists, wood or steel deck',
        walls: 'Brick or concrete block masonry, tilt-up formed concrete'
    },
    D: {
        framing: 'Wood or steel studs in bearing wall, wood or steel skeleton frame',
        floor: 'Wood or steel floor joints or slab on ground',
        roof: 'Wood or steel joists, wood or steel deck',
        walls: 'Any material except masonry or concrete'
    },
    'C+D': {
        description: 'Mixtures of characters of construction'
    },
    'D/C': {
        description: 'Character of construction is a Class D with an exterior cladding of a higher cost than normal character of construction D specifications'
    },
    'N/A': {
        description: 'Not applicable'
    }
};
export const yearBuiltCodeNames = {
    E: 'Estimated R Renovated A Addition',
    B: 'both Estimated and Renovated',
    C: 'both Estimated and Addition',
    D: 'both Renovated and Addition',
    M: 'Estimated, Renovated and Addition',
    N: 'none of the above codes are applicable'
};
export const conditionCodes = {
    E: { ranking: 5, name: 'Excellent' },
    G: { ranking: 4, name: 'Good' },
    A: { ranking: 3, name: 'Average' },
    F: { ranking: 2, name: 'Fair' },
    P: { ranking: 1, name: 'Poor' }
};
export const partStoreyCodeNames = {
    1: '1/4 storey',
    2: '1/2 storey',
    3: '3/4 storey'
};
export const splitCodeNames = {
    B: 'Back or Front Split',
    S: 'Side Split',
    Y: 'Yes (unconventional split style)',
    N: 'No Split'
};
export const basementFinishCodeNames = {
    R: 'Recreation',
    A: 'Apartment'
};
export const heatingTypeCodeNames = {
    FA: 'Forced Air',
    HW: 'Hot Water',
    EL: 'Electric Heating',
    GR: 'Gravity Hot Air',
    PL: 'Pipeless Hot Air',
    RD: 'Radiant Electric',
    OT: 'Other',
    NO: 'No Central Heating System'
};
export const garageTypeCodeNames = {
    A: 'Attached',
    I: 'Indoor',
    B: 'Basement or Built-in',
    M: 'More than one type is present',
    C: 'Carport',
    N: 'No parking or No garage',
    D: 'Detached',
    P: 'Parking'
};
export const structureCodeClasses = {
    100: 'Secondary',
    200: 'Farm',
    300: 'Residential',
    400: 'Commercial',
    500: 'Industrial',
    600: 'Institutional',
    700: 'Special Purpose'
};
export const structureCodeNames = {
    101: 'Detached Garage',
    102: 'Shed',
    103: 'Greenhouse',
    104: 'Workshop',
    105: 'Boathouse',
    106: 'Indoor Pool',
    107: 'Swimming Pool Enclosures',
    108: 'Outdoor Pool',
    109: 'Tennis Court',
    110: 'Boathouse with Residence Above',
    115: 'Summer Kitchen',
    116: 'Attached Garage',
    117: 'Carport',
    118: 'Cabin',
    119: 'Detached Garage with Residence Above',
    120: 'Workshop with Residence Above',
    121: 'Basement Garage',
    122: 'Gazebo',
    123: 'Pool House/Cabana',
    124: 'Private Studio (Detached)',
    125: 'Outdoor Fireplace',
    126: 'Outdoor Kitchen/Bar',
    127: 'Outdoor Sauna/Hot Tub',
    128: 'Boat Port',
    129: 'Timeshare - Bachelor Unit',
    130: 'Timeshare - One or More Bedroom Units',
    150: 'Site Improvements',
    151: 'Solarium',
    161: 'Helipad',
    162: 'Equipment',
    163: 'Shipping Container / Sea-can',
    199: 'Other Secondary Structure',
    201: 'Type I Barn',
    202: 'Type II Barn',
    203: 'Type III Uninsulated Barn',
    204: 'Type IV Insulated Barn',
    211: 'Milk House',
    212: 'Milking Parlour (In Barn)',
    215: 'Single Storey Caged Pullets',
    216: 'Broiler Barns',
    217: 'High Rise Caged Layers',
    220: 'Silo / Open Top',
    224: 'Concrete Oxygen Limiting Silo',
    225: 'Metal Oxygen Limiting Silo',
    226: 'Feedstore Silo',
    227: 'Harvestore Silo',
    228: 'Sealstor Silo',
    229: 'Horizontal Silo',
    230: 'Steel Grain Bin',
    232: 'Circular Bulk Feed Tank',
    234: 'Rectangular Bulk Feed Tank',
    236: 'Circular Steel Corn Crib',
    237: 'Wood Corn Crib',
    238: 'Drive Through Corn Crib',
    240: 'Pack Barn',
    242: 'Interior Stripper Room',
    244: 'Standard Kiln',
    245: 'Bulk Kiln',
    250: 'Greenhouse (Freestanding)',
    252: 'Greenhouse (Ridge and Valley) 2A',
    254: 'Greenhouse (Ridge and Valley) 2B',
    256: 'Greenhouse (Bow or Curved)',
    258: 'Greenhouse (Economy)',
    260: 'Fruit and Vegetable Pallet',
    262: 'Fruit and Vegetable Bulk',
    264: 'Mink Shed',
    266: 'Prefab. Metal (Straight)',
    268: 'Prefab. Metal (Slant)',
    270: 'Quonset',
    275: 'Miscellaneous Shed',
    282: 'Rectangular Tank (Slatted Floor)',
    284: 'Freestanding Rectangular Tank',
    286: 'Circular Concrete Tank',
    288: 'Liquid Manure Steel Tank',
    289: 'Coverall',
    299: 'Unspecified Farm Building',
    301: 'Single Family Detached',
    302: 'Single Family Semi-Detached',
    303: 'Single Family Row/Town House',
    304: 'Link Home (Cost Detached)',
    305: 'Link Home (Cost Semi-Detached)',
    310: 'Mobile Home',
    311: 'Trailer',
    312: 'Park Model Trailer',
    313: 'Recreational Park Model Trailer',
    322: 'Duplex',
    323: 'Triplex',
    324: 'Fourplex',
    325: 'Fiveplex',
    326: 'Sixplex',
    330: 'Walkup Apartment, Greater Than 6 Units, 1-4 Floors',
    331: 'Medium/High Rise Appartment, Greater Than 6 Units',
    340: 'Row/Town House Rental',
    341: 'Stacked Row/Town House Rental',
    350: 'Condo Single Family Detached',
    351: 'Condo Single Family Semi-Detached',
    352: 'Condo Apartment in a Walkup',
    353: 'Condo Apartment in a Medium/High Rise',
    354: 'Condo Row/Town House',
    355: 'Condo Stacked Town House',
    356: 'Condominium Parking Space',
    357: 'Condominium Locker',
    358: 'Combined Parking and Locker Unit',
    359: 'Condo - Private Workshop',
    360: 'Condo - Private Wine Cellar',
    361: 'Condo - Private Studio',
    362: 'Condo - Private Rooftop Terrace',
    399: 'Unspecified Residential Structure',
    401: 'Multi-Use Multi Storey Building',
    412: 'Apartment in a Non-Residential Structure',
    422: 'Service Station',
    423: 'Service Garage',
    424: 'Automotive Show Room',
    425: 'Gas Bar Kiosk',
    426: 'Car Wash (Automatic)',
    427: 'Automotive Specialty Shop',
    428: 'Gas Bar Canopy',
    429: 'Car Wash (Coin Operated)',
    433: 'Retail Store',
    434: 'Shopping Centre - Neighbourhood',
    435: 'Shopping Centre - Community',
    436: 'Shopping Centre - Regional',
    437: 'Discount Store',
    438: 'Big Box Retail',
    439: 'Supermarket',
    442: 'Conventional Restaurant',
    443: 'Fast Food Restaurant',
    452: 'Bank/Trust Company',
    454: 'Mini Bank/Trust Building',
    460: 'Assembly/Banquet Hall/Convention Centre',
    461: 'Campground Ancilliary Building',
    462: 'Live Theatre',
    463: 'Cinema',
    464: 'Drive-In Screen',
    465: 'Squash/Racquetball Court',
    466: 'Recreational Swimming Pool',
    467: 'Marina Ancilliary Building',
    468: 'Ski-Lift',
    469: 'Commercial Tennis Court',
    470: 'Water and/or Dry Slide',
    472: 'Office Commercial',
    473: 'Office Walkup, Medical and Dental',
    474: 'Office, Multi-Storey',
    482: 'Hotel',
    484: 'Motel',
    490: 'Tower',
    491: 'Retail Kiosk (Indoor)',
    492: 'Billboard',
    493: 'Photo Kiosk (Outdoor)',
    494: 'Commercial Warehouse',
    495: 'Parking Garage',
    496: 'Underground Parking',
    499: 'Unspecified Commercial Building',
    501: 'Pipelines, Compressor Station',
    502: 'Bridge',
    503: 'Transformer',
    504: 'Pole',
    505: 'Post and Beam Frame',
    506: 'Wood Frame',
    507: 'Prefabricated',
    508: 'Load Bearing',
    509: 'Steel Frame',
    510: 'Pre-Engineered',
    522: 'General Purpose / Miscellaneous',
    523: 'Special Purpose',
    524: 'Industrial Malls',
    525: 'Reinforced Concrete Frame',
    526: 'Precast Concrete Frame',
    527: 'Wood-Framed Industrial Structure',
    528: 'Mini Storage Warehouse',
    532: 'Prefabricated Structure - Clr Span',
    533: 'Prefabricated Structure - Multispan',
    534: 'Prefabricated Structure - Arched',
    542: 'Office Industrial',
    551: 'Industrial Wharves and Jetties',
    552: 'Miscellaneous Industrial (Less Than 5000 SQ FT)',
    553: 'Conveyor Housing',
    554: 'Bin/Hopper',
    555: 'Gatehouse',
    556: 'Tunnel',
    557: 'Industrial Silo',
    558: 'Lumber Storage Shed',
    559: 'Tank',
    567: 'Wind Turbine',
    568: 'Solar Thermal (Solar Panels)',
    569: 'Anaerobic Digester',
    572: 'Truck Terminals',
    582: 'Communications Building',
    592: 'Grain Elevator',
    593: 'Feed Mill',
    594: 'Industrial Miscellaneous Components',
    595: 'Mine',
    596: 'Heavy Industry',
    597: 'Standard Industry',
    598: 'Warehousing',
    599: 'Unspecified Industrial Building',
    600: 'University/College Spec Structure',
    608: 'Daycare Purpose Built',
    610: 'Nursing/Retirement Home',
    620: 'Hospital',
    630: 'Penal/Correctional Building',
    640: 'Dormitory',
    645: 'Institutional Residence',
    650: 'Secondary School',
    660: 'Elementary School',
    661: 'Portable Classroom',
    699: 'Unspecified Institutional Structure',
    705: 'Funeral Home Purpose Built',
    709: 'Rink',
    710: 'Arena',
    711: 'Bowling Alley',
    725: 'Armoury',
    730: 'Traditional Church',
    731: 'Contemporary Church',
    732: 'Library',
    740: 'Airplane Hanger',
    750: 'Mausoleum',
    760: 'Police Station',
    770: 'Firehall',
    780: 'Grandstand/Stadium',
    790: 'Exhibit Building/Museum/Gallery',
    799: 'Unspecified Special Purpose Structure'
};
export const textureCodeNames = {
    0: 'Non-farm land',
    1: 'Sand',
    2: 'Sandy loam',
    3: 'Silt loam, loam',
    4: 'Clay loam',
    5: 'Clay',
    6: 'Swamp',
    7: 'Organic',
    8: 'Water',
    9: 'Rock'
};
