export declare const propertyCodeClasses: Readonly<{
    100: "Land";
    200: "Farm";
    300: "Residential";
    400: "Commercial";
    500: "Industrial";
    600: "Institutional";
    700: "Special Purpose";
    800: "Government";
}>;
export declare const propertyCodeNames: Readonly<{
    '100': "Vacant residential land not on water";
    '101': "Second tier vacant lot";
    '102': "Conservation Authority land";
    '103': "Municipal park";
    '105': "Vacant commercial land";
    '106': "Vacant industrial land";
    '107': "Provincial park";
    '108': "Federal park";
    '109': "Large land holdings, greater than 1000 acres";
    '110': "Vacant residential/recreational land on water";
    '111': "Island under single ownership";
    '112': "Multi-residential vacant land";
    '113': "Condominium development land - residential (vacant lot)";
    '114': "Condominium development land - non residential (vacant lot)";
    '115': "Property in process of redevelopment utilizing existing structure(s)";
    '120': "Water lot (entirely under water)";
    '125': "Residential development land";
    '127': "Townhouse block - freehold units";
    '130': "Non-buildable land";
    '134': "Land designated and zoned for open space";
    '140': "Common land";
    '150': "Mining lands - patented";
    '151': "Mining lands - unpatented";
    '155': "Land associated with power dam";
    '169': "Vacant land condominium (residential)";
    '200': "Farm property without any buildings/structures";
    '201': "Farm with residence - with or without secondary structures; no farm outbuildings";
    '210': "Farm without residence - with secondary structures; with farm outbuildings";
    '211': "Farm with residence - with or without secondary structures; with farm outbuildings";
    '220': "Farm without residence - with commercial/industrial operation";
    '221': "Farm with residence - with commercial/industrial operation";
    '222': "Farm with a winery";
    '223': "Grain/seed and feed operation";
    '224': "Tobacco farm";
    '225': "Ginseng farm";
    '226': "Exotic farms";
    '227': "Nut Orchard";
    '228': "Farm with gravel pit";
    '229': "Farm with campground/mobile home park";
    '230': "Intensive farm operation - without residence";
    '231': "Intensive farm operation - with residence";
    '232': "Large scale greenhouse operation";
    '233': "Large scale swine operation";
    '234': "Large scale poultry operation";
    '235': "Government - agriculture research facility";
    '236': "Farm with oil/gas well(s)";
    '240': "Managed forest property, vacant land not on water";
    '241': "Managed forest property, vacant land on water";
    '242': "Managed forest property, seasonal residence not on water";
    '243': "Managed forest property, seasonal residence on water";
    '244': "Managed forest property, residence not on water";
    '245': "Managed forest property, residence on water";
    '260': "Vacant residential/commercial/ industrial land owned by a non-farmer with a portion being farmed";
    '261': "Land owned by a non-farmer improved with a non-farm residence with a portion being farmed";
    '262': "Land owned by a farmer improved with a non-farm residence with a portion being farmed";
    '301': "Single family detached (not on water)";
    '302': "More than one structure used for residential purposes";
    '303': "Residence with a commercial unit";
    '304': "Residence with a commercial/ industrial use building";
    '305': "Link home";
    '306': "Boathouse with residence above";
    '307': "Community lifestyle (not a mobile home park)";
    '309': "Freehold Townhouse/Row house";
    '311': "Semi-detached residential";
    '313': "Single family detached on water";
    '314': "Clergy Residence";
    '322': "Semi-detached residence with both units under one ownership";
    '332': "Residential structure with two self-contained units.";
    '333': "Residential property with three self-contained units";
    '334': "Residential property with four self-contained units";
    '335': "Residential property with five self-contained units";
    '336': "Residential property with six self-contained units";
    '340': "Multi-residential, with 7 or more self-contained units";
    '341': "Multi-residential, with 7 or more self-contained residential units, with small commercial unit(s)";
    '350': "Row housing, with three to six units under single ownership";
    '352': "Row housing, with seven or more units under single ownership";
    '360': "Rooming or boarding house";
    '361': "Bachelorette";
    '363': "House-keeping cottages - no American plan";
    '364': "House-keeping cottages - less than 50% American plan";
    '365': "Group Home";
    '366': "Student housing (off campus)";
    '367': "Service or amenity unit";
    '368': "Residential Dockominium";
    '369': "Vacant land condominium (residential - improved)";
    '370': "Residential Condominium Unit";
    '371': "Life Lease - No Redemption.";
    '372': "Life Lease - Return on Invest.";
    '373': "Cooperative housing - equity";
    '374': "Cooperative housing - non-equity";
    '375': "Co-ownership";
    '376': "Condominium locker unit - separately deeded.";
    '377': "Condominium parking space/unit - separately deeded.";
    '378': "Residential Leasehold Condominium Corporation";
    '379': "Residential phased condominium corporation";
    '380': "Residential common elements condominium corporation";
    '381': "Mobile home";
    '382': "Mobile home park";
    '383': "Bed and breakfast establishment";
    '385': "Time-share, fee simple";
    '386': "Time share, right-to-use";
    '391': "Seasonal/recreational dwelling - first tier on water";
    '392': "Seasonal/recreational dwelling - second tier to water";
    '395': "Seasonal/recreational dwelling - not located on water";
    '400': "Small Office building";
    '401': "Small Medical/dental building";
    '402': "Large office building";
    '403': "Large medical/dental building";
    '405': "Office use converted from house";
    '406': "Retail use converted from house";
    '407': "Retail lumber yard";
    '408': "Freestanding Beer Store or LCBO";
    '409': "Retail";
    '410': "Retail";
    '411': "Restaurant - conventional";
    '412': "Restaurant - fast food";
    '413': "Restaurant - conventional, national chain";
    '414': "Restaurant - fast food, national chain";
    '415': "Cinema/movie house/drive-in";
    '416': "Concert hall/live theatre";
    '417': "Entertainment complex";
    '419': "Automotive service centre, highway - 400 series highways";
    '420': "Automotive fuel station with or without service facilities";
    '421': "Specialty automotive shop";
    '422': "Auto dealership";
    '423': "Auto dealership";
    '425': "Neighbourhood shopping centre";
    '426': "Small box shopping centre";
    '427': "Big box shopping/power centre";
    '428': "Regional shopping centre";
    '429': "Community shopping centre";
    '430': "Neighbourhood shopping centre";
    '431': "Department store";
    '432': "Banks and similar financial institutions, including credit unions";
    '433': "Banks and similar financial institutions, including credit unions";
    '434': "Freestanding supermarket";
    '435': "Large retail building centre";
    '436': "Freestanding large retail store, national chain";
    '438': "Neighbourhood shopping centre with offices above";
    '441': "Tavern/public house/small hotel";
    '444': "Full service hotel";
    '445': "Limited service hotel";
    '446': "Apartment hotel";
    '447': "Condominium Hotel Unit";
    '450': "Motel";
    '451': "Seasonal motel";
    '460': "Resort hotel";
    '461': "Resort lodge";
    '462': "Country inns & small inns";
    '463': "Fishing/hunting lodges/resorts";
    '465': "Child and community oriented camp/resort";
    '470': "Multi-type complex";
    '471': "Retail or office with residential unit(s) above or behind";
    '472': "Retail or office with residential unit(s) above or behind";
    '473': "Retail with more than one non-retail use";
    '475': "Commercial condominium";
    '476': "Commercial condominium (live/work)";
    '477': "Retail with office(s)";
    '478': "Retail with office(s)";
    '480': "Surface parking lot";
    '481': "Parking garage";
    '482': "Surface parking lot";
    '483': "Parking garage";
    '486': "Campground";
    '487': "Billboard";
    '489': "Driving range/golf centre";
    '490': "Golf course";
    '491': "Ski resort";
    '492': "Marina - located on waterfront";
    '493': "Marina - not located on waterfront";
    '495': "Communication towers";
    '496': "Communication buildings";
    '500': "Mines - active";
    '501': "Mines - inactive";
    '502': "Mine tailings site associated with an active mine";
    '503': "Mine tailings site not associated with an active mine";
    '504': "Oil/gas wells";
    '505': "Sawmill/lumber mill";
    '506': "Forest products";
    '510': "Heavy manufacturing (non-automotive)";
    '511': "Pulp and paper mill";
    '512': "Cement/asphalt manufacturing plant";
    '513': "Steel mill";
    '514': "Automotive assembly plant";
    '515': "Shipyard/dry-dock";
    '516': "Automotive parts production plant";
    '517': "Specialty steel production (mini-mills)";
    '518': "Smelter/ore processing";
    '519': "Foundry";
    '520': "Standard industrial properties not specifically identified by other industrial Property Codes";
    '521': "Distillery/brewery";
    '522': "Grain elevators - Great Lakes waterway";
    '523': "Grain handling - Primary elevators (including feed mills)";
    '525': "Process elevators - flour mills, oilseed crushing, malt houses";
    '527': "Abattoir/slaughter house/rendering plants";
    '528': "Food processing plant";
    '529': "Freezer plant/cold storage";
    '530': "Warehousing";
    '531': "Mini-warehousing";
    '532': "Dry Cleaning Plant";
    '535': "Research and development facilities";
    '540': "Other industrial";
    '541': "Printing plant";
    '544': "Truck terminal";
    '545': "Major distribution centre";
    '550': "Petro-chemical plant";
    '551': "Oil refinery";
    '552': "Tank farm";
    '553': "Bulk oil/fuel distribution terminal";
    '555': "O.P.G. Hydraulic Generating Station";
    '556': "O.P.G. Nuclear Generating Station";
    '557': "O.P.G. Fossil Generating Station";
    '558': "Hydro One Transformer Station";
    '559': "MEU Generating Station";
    '560': "MEU Transformer Station";
    '561': "Hydro One Right-of-Way";
    '562': "Private Hydro Rights-of-Way";
    '563': "Private Hydraulic Generating Station";
    '564': "Private Nuclear Generating Station";
    '565': "Private Generating Station (Fossil Fuels and Cogen)";
    '566': "Private Transformer Station";
    '567': "Wind Turbine";
    '568': "Solar/Photo Voltaic Electricity Generating Facility";
    '575': "Industrial condominium";
    '580': "Industrial mall";
    '588': "Pipelines";
    '589': "Compressor station";
    '590': "Water treatment/filtration/water towers/pumping station";
    '591': "Sewage treatment/waste pumping/waste disposal";
    '592': "Dump/transfer station/incineration plant/landfill";
    '593': "Gravel pit, quarry, sand pit";
    '594': "Peat moss operation";
    '595': "Heat or steam plant";
    '596': "Recycling facility";
    '597': "Railway right-of-way";
    '598': "Railway buildings and lands described as assessable in the Assessment Act";
    '599': "GO transit station/rail yard";
    '601': "Post secondary education";
    '602': "Multiple occupancy educational institutional residence located on or off campus";
    '605': "School";
    '608': "Day Care";
    '610': "Other educational institution";
    '611': "Other institutional residence";
    '621': "Hospital, private or public";
    '623': "Continuum of care seniors facility";
    '624': "Retirement/nursing home (combined)";
    '625': "Nursing home";
    '626': "Old age/retirement home";
    '627': "Other health care facility";
    '630': "Federal penitentiary or correctional facility";
    '631': "Provincial correctional facility";
    '632': "Other correctional facility";
    '700': "Place of worship - with a clergy residence";
    '701': "Place of Worship - without a clergy residence";
    '702': "Cemetery";
    '703': "Cemetery with non-internment services";
    '704': "Crematorium";
    '705': "Funeral Home";
    '710': "Recreational sport club - non commercial";
    '711': "Bowling alley";
    '713': "Casino";
    '715': "Racetrack - auto";
    '716': "Racetrack - horse, with slot facility";
    '717': "Racetrack - horse, without slot facility";
    '718': "Exhibition grounds/fair grounds";
    '720': "Commercial sport complex";
    '721': "Non-commercial sports complex";
    '722': "Professional sports complex";
    '725': "Amusement park";
    '726': "Amusement park - large/regional";
    '730': "Museum and/or art gallery";
    '731': "Library and/or literary institutions";
    '733': "Convention, conference, congress centre";
    '734': "Banquet hall";
    '735': "Assembly hall, community hall";
    '736': "Clubs - private, fraternal";
    '737': "Federal airport";
    '738': "Provincial airport";
    '739': "Local government airport";
    '740': "Airport leasehold";
    '741': "Airport Authority";
    '742': "Public transportation - easements and rights";
    '743': "International bridge/tunnel";
    '744': "Private airport/hangar";
    '745': "Recreational airport";
    '746': "Subway station";
    '748': "Transit garage";
    '749': "Public transportation - other";
    '750': "Scientific, pharmaceutical, medical research facility (structures predominantly other than office)";
    '755': "Lighthouses";
    '760': "Military base or camp (CFB)";
    '761': "Armoury";
    '762': "Military education facility";
    '805': "Post office or depot";
    '806': "Postal mechanical sorting facility";
    '810': "Fire Hall";
    '812': "Ambulance Station";
    '815': "Police Station";
    '822': "Government - agricultural research facility";
    '824': "Government - wharves and harbours";
    '826': "Government - special educational facility";
    '828': "Government - canals and locks";
    '830': "Government - navigational facilities";
    '832': "Government - historic site or monument";
    '840': "Port authority - port activities";
    '842': "Port authority - other activities";
}>;
export declare const serviceCodeNames: Readonly<{
    A: "All Services";
    H: "Hydro Access";
    M: "Municipal Water";
    N: "No Services";
    P: "Part Services";
    S: "Sanitary Services";
    T: "Septic System";
    W: "Well Water";
    X: "No Water";
    Y: "No Water Disposal";
}>;
export declare const accessCodeNames: Readonly<{
    Y: "Year Round Access by Road";
    I: "Island Access";
    L: "Land Locked";
    N: "No Road Access";
    O: "Private Road Access";
    R: "Right-of-Way Access";
    S: "Summer or Seasonal Access Only";
    W: "Water Access Only";
}>;
