export declare const propertyCodeClasses: {
    readonly 100: "Land";
    readonly 200: "Farm";
    readonly 300: "Residential";
    readonly 400: "Commercial";
    readonly 500: "Industrial";
    readonly 600: "Institutional";
    readonly 700: "Special Purpose";
    readonly 800: "Government";
};
export declare const propertyCodeNames: {
    readonly '100': "Vacant residential land not on water";
    readonly '101': "Second tier vacant lot";
    readonly '102': "Conservation Authority land";
    readonly '103': "Municipal park";
    readonly '105': "Vacant commercial land";
    readonly '106': "Vacant industrial land";
    readonly '107': "Provincial park";
    readonly '108': "Federal park";
    readonly '109': "Large land holdings, greater than 1000 acres";
    readonly '110': "Vacant residential/recreational land on water";
    readonly '111': "Island under single ownership";
    readonly '112': "Multi-residential vacant land";
    readonly '113': "Condominium development land - residential (vacant lot)";
    readonly '114': "Condominium development land - non residential (vacant lot)";
    readonly '115': "Property in process of redevelopment utilizing existing structure(s)";
    readonly '120': "Water lot (entirely under water)";
    readonly '125': "Residential development land";
    readonly '127': "Townhouse block - freehold units";
    readonly '130': "Non-buildable land";
    readonly '134': "Land designated and zoned for open space";
    readonly '140': "Common land";
    readonly '150': "Mining lands - patented";
    readonly '151': "Mining lands - unpatented";
    readonly '155': "Land associated with power dam";
    readonly '169': "Vacant land condominium (residential)";
    readonly '200': "Farm property without any buildings/structures";
    readonly '201': "Farm with residence - with or without secondary structures; no farm outbuildings";
    readonly '210': "Farm without residence - with secondary structures; with farm outbuildings";
    readonly '211': "Farm with residence - with or without secondary structures; with farm outbuildings";
    readonly '220': "Farm without residence - with commercial/industrial operation";
    readonly '221': "Farm with residence - with commercial/industrial operation";
    readonly '222': "Farm with a winery";
    readonly '223': "Grain/seed and feed operation";
    readonly '224': "Tobacco farm";
    readonly '225': "Ginseng farm";
    readonly '226': "Exotic farms";
    readonly '227': "Nut Orchard";
    readonly '228': "Farm with gravel pit";
    readonly '229': "Farm with campground/mobile home park";
    readonly '230': "Intensive farm operation - without residence";
    readonly '231': "Intensive farm operation - with residence";
    readonly '232': "Large scale greenhouse operation";
    readonly '233': "Large scale swine operation";
    readonly '234': "Large scale poultry operation";
    readonly '235': "Government - agriculture research facility";
    readonly '236': "Farm with oil/gas well(s)";
    readonly '240': "Managed forest property, vacant land not on water";
    readonly '241': "Managed forest property, vacant land on water";
    readonly '242': "Managed forest property, seasonal residence not on water";
    readonly '243': "Managed forest property, seasonal residence on water";
    readonly '244': "Managed forest property, residence not on water";
    readonly '245': "Managed forest property, residence on water";
    readonly '260': "Vacant residential/commercial/ industrial land owned by a non-farmer with a portion being farmed";
    readonly '261': "Land owned by a non-farmer improved with a non-farm residence with a portion being farmed";
    readonly '262': "Land owned by a farmer improved with a non-farm residence with a portion being farmed";
    readonly '301': "Single family detached (not on water)";
    readonly '302': "More than one structure used for residential purposes";
    readonly '303': "Residence with a commercial unit";
    readonly '304': "Residence with a commercial/ industrial use building";
    readonly '305': "Link home";
    readonly '306': "Boathouse with residence above";
    readonly '307': "Community lifestyle (not a mobile home park)";
    readonly '309': "Freehold Townhouse/Row house";
    readonly '311': "Semi-detached residential";
    readonly '313': "Single family detached on water";
    readonly '314': "Clergy Residence";
    readonly '322': "Semi-detached residence with both units under one ownership";
    readonly '332': "Residential structure with two self-contained units.";
    readonly '333': "Residential property with three self-contained units";
    readonly '334': "Residential property with four self-contained units";
    readonly '335': "Residential property with five self-contained units";
    readonly '336': "Residential property with six self-contained units";
    readonly '340': "Multi-residential, with 7 or more self-contained units";
    readonly '341': "Multi-residential, with 7 or more self-contained residential units, with small commercial unit(s)";
    readonly '350': "Row housing, with three to six units under single ownership";
    readonly '352': "Row housing, with seven or more units under single ownership";
    readonly '360': "Rooming or boarding house";
    readonly '361': "Bachelorette";
    readonly '363': "House-keeping cottages - no American plan";
    readonly '364': "House-keeping cottages - less than 50% American plan";
    readonly '365': "Group Home";
    readonly '366': "Student housing (off campus)";
    readonly '367': "Service or amenity unit";
    readonly '368': "Residential Dockominium";
    readonly '369': "Vacant land condominium (residential - improved)";
    readonly '370': "Residential Condominium Unit";
    readonly '371': "Life Lease - No Redemption.";
    readonly '372': "Life Lease - Return on Invest.";
    readonly '373': "Cooperative housing - equity";
    readonly '374': "Cooperative housing - non-equity";
    readonly '375': "Co-ownership";
    readonly '376': "Condominium locker unit - separately deeded.";
    readonly '377': "Condominium parking space/unit - separately deeded.";
    readonly '378': "Residential Leasehold Condominium Corporation";
    readonly '379': "Residential phased condominium corporation";
    readonly '380': "Residential common elements condominium corporation";
    readonly '381': "Mobile home";
    readonly '382': "Mobile home park";
    readonly '383': "Bed and breakfast establishment";
    readonly '385': "Time-share, fee simple";
    readonly '386': "Time share, right-to-use";
    readonly '391': "Seasonal/recreational dwelling - first tier on water";
    readonly '392': "Seasonal/recreational dwelling - second tier to water";
    readonly '395': "Seasonal/recreational dwelling - not located on water";
    readonly '400': "Small Office building";
    readonly '401': "Small Medical/dental building";
    readonly '402': "Large office building";
    readonly '403': "Large medical/dental building";
    readonly '405': "Office use converted from house";
    readonly '406': "Retail use converted from house";
    readonly '407': "Retail lumber yard";
    readonly '408': "Freestanding Beer Store or LCBO";
    readonly '409': "Retail";
    readonly '410': "Retail";
    readonly '411': "Restaurant - conventional";
    readonly '412': "Restaurant - fast food";
    readonly '413': "Restaurant - conventional, national chain";
    readonly '414': "Restaurant - fast food, national chain";
    readonly '415': "Cinema/movie house/drive-in";
    readonly '416': "Concert hall/live theatre";
    readonly '417': "Entertainment complex";
    readonly '419': "Automotive service centre, highway - 400 series highways";
    readonly '420': "Automotive fuel station with or without service facilities";
    readonly '421': "Specialty automotive shop";
    readonly '422': "Auto dealership";
    readonly '423': "Auto dealership";
    readonly '425': "Neighbourhood shopping centre";
    readonly '426': "Small box shopping centre";
    readonly '427': "Big box shopping/power centre";
    readonly '428': "Regional shopping centre";
    readonly '429': "Community shopping centre";
    readonly '430': "Neighbourhood shopping centre";
    readonly '431': "Department store";
    readonly '432': "Banks and similar financial institutions, including credit unions";
    readonly '433': "Banks and similar financial institutions, including credit unions";
    readonly '434': "Freestanding supermarket";
    readonly '435': "Large retail building centre";
    readonly '436': "Freestanding large retail store, national chain";
    readonly '438': "Neighbourhood shopping centre with offices above";
    readonly '441': "Tavern/public house/small hotel";
    readonly '444': "Full service hotel";
    readonly '445': "Limited service hotel";
    readonly '446': "Apartment hotel";
    readonly '447': "Condominium Hotel Unit";
    readonly '450': "Motel";
    readonly '451': "Seasonal motel";
    readonly '460': "Resort hotel";
    readonly '461': "Resort lodge";
    readonly '462': "Country inns & small inns";
    readonly '463': "Fishing/hunting lodges/resorts";
    readonly '465': "Child and community oriented camp/resort";
    readonly '470': "Multi-type complex";
    readonly '471': "Retail or office with residential unit(s) above or behind";
    readonly '472': "Retail or office with residential unit(s) above or behind";
    readonly '473': "Retail with more than one non-retail use";
    readonly '475': "Commercial condominium";
    readonly '476': "Commercial condominium (live/work)";
    readonly '477': "Retail with office(s)";
    readonly '478': "Retail with office(s)";
    readonly '480': "Surface parking lot";
    readonly '481': "Parking garage";
    readonly '482': "Surface parking lot";
    readonly '483': "Parking garage";
    readonly '486': "Campground";
    readonly '487': "Billboard";
    readonly '489': "Driving range/golf centre";
    readonly '490': "Golf course";
    readonly '491': "Ski resort";
    readonly '492': "Marina - located on waterfront";
    readonly '493': "Marina - not located on waterfront";
    readonly '495': "Communication towers";
    readonly '496': "Communication buildings";
    readonly '500': "Mines - active";
    readonly '501': "Mines - inactive";
    readonly '502': "Mine tailings site associated with an active mine";
    readonly '503': "Mine tailings site not associated with an active mine";
    readonly '504': "Oil/gas wells";
    readonly '505': "Sawmill/lumber mill";
    readonly '506': "Forest products";
    readonly '510': "Heavy manufacturing (non-automotive)";
    readonly '511': "Pulp and paper mill";
    readonly '512': "Cement/asphalt manufacturing plant";
    readonly '513': "Steel mill";
    readonly '514': "Automotive assembly plant";
    readonly '515': "Shipyard/dry-dock";
    readonly '516': "Automotive parts production plant";
    readonly '517': "Specialty steel production (mini-mills)";
    readonly '518': "Smelter/ore processing";
    readonly '519': "Foundry";
    readonly '520': "Standard industrial properties not specifically identified by other industrial Property Codes";
    readonly '521': "Distillery/brewery";
    readonly '522': "Grain elevators - Great Lakes waterway";
    readonly '523': "Grain handling - Primary elevators (including feed mills)";
    readonly '525': "Process elevators - flour mills, oilseed crushing, malt houses";
    readonly '527': "Abattoir/slaughter house/rendering plants";
    readonly '528': "Food processing plant";
    readonly '529': "Freezer plant/cold storage";
    readonly '530': "Warehousing";
    readonly '531': "Mini-warehousing";
    readonly '532': "Dry Cleaning Plant";
    readonly '535': "Research and development facilities";
    readonly '540': "Other industrial";
    readonly '541': "Printing plant";
    readonly '544': "Truck terminal";
    readonly '545': "Major distribution centre";
    readonly '550': "Petro-chemical plant";
    readonly '551': "Oil refinery";
    readonly '552': "Tank farm";
    readonly '553': "Bulk oil/fuel distribution terminal";
    readonly '555': "O.P.G. Hydraulic Generating Station";
    readonly '556': "O.P.G. Nuclear Generating Station";
    readonly '557': "O.P.G. Fossil Generating Station";
    readonly '558': "Hydro One Transformer Station";
    readonly '559': "MEU Generating Station";
    readonly '560': "MEU Transformer Station";
    readonly '561': "Hydro One Right-of-Way";
    readonly '562': "Private Hydro Rights-of-Way";
    readonly '563': "Private Hydraulic Generating Station";
    readonly '564': "Private Nuclear Generating Station";
    readonly '565': "Private Generating Station (Fossil Fuels and Cogen)";
    readonly '566': "Private Transformer Station";
    readonly '567': "Wind Turbine";
    readonly '568': "Solar/Photo Voltaic Electricity Generating Facility";
    readonly '575': "Industrial condominium";
    readonly '580': "Industrial mall";
    readonly '588': "Pipelines";
    readonly '589': "Compressor station";
    readonly '590': "Water treatment/filtration/water towers/pumping station";
    readonly '591': "Sewage treatment/waste pumping/waste disposal";
    readonly '592': "Dump/transfer station/incineration plant/landfill";
    readonly '593': "Gravel pit, quarry, sand pit";
    readonly '594': "Peat moss operation";
    readonly '595': "Heat or steam plant";
    readonly '596': "Recycling facility";
    readonly '597': "Railway right-of-way";
    readonly '598': "Railway buildings and lands described as assessable in the Assessment Act";
    readonly '599': "GO transit station/rail yard";
    readonly '601': "Post secondary education";
    readonly '602': "Multiple occupancy educational institutional residence located on or off campus";
    readonly '605': "School";
    readonly '608': "Day Care";
    readonly '610': "Other educational institution";
    readonly '611': "Other institutional residence";
    readonly '621': "Hospital, private or public";
    readonly '623': "Continuum of care seniors facility";
    readonly '624': "Retirement/nursing home (combined)";
    readonly '625': "Nursing home";
    readonly '626': "Old age/retirement home";
    readonly '627': "Other health care facility";
    readonly '630': "Federal penitentiary or correctional facility";
    readonly '631': "Provincial correctional facility";
    readonly '632': "Other correctional facility";
    readonly '700': "Place of worship - with a clergy residence";
    readonly '701': "Place of Worship - without a clergy residence";
    readonly '702': "Cemetery";
    readonly '703': "Cemetery with non-internment services";
    readonly '704': "Crematorium";
    readonly '705': "Funeral Home";
    readonly '710': "Recreational sport club - non commercial";
    readonly '711': "Bowling alley";
    readonly '713': "Casino";
    readonly '715': "Racetrack - auto";
    readonly '716': "Racetrack - horse, with slot facility";
    readonly '717': "Racetrack - horse, without slot facility";
    readonly '718': "Exhibition grounds/fair grounds";
    readonly '720': "Commercial sport complex";
    readonly '721': "Non-commercial sports complex";
    readonly '722': "Professional sports complex";
    readonly '725': "Amusement park";
    readonly '726': "Amusement park - large/regional";
    readonly '730': "Museum and/or art gallery";
    readonly '731': "Library and/or literary institutions";
    readonly '733': "Convention, conference, congress centre";
    readonly '734': "Banquet hall";
    readonly '735': "Assembly hall, community hall";
    readonly '736': "Clubs - private, fraternal";
    readonly '737': "Federal airport";
    readonly '738': "Provincial airport";
    readonly '739': "Local government airport";
    readonly '740': "Airport leasehold";
    readonly '741': "Airport Authority";
    readonly '742': "Public transportation - easements and rights";
    readonly '743': "International bridge/tunnel";
    readonly '744': "Private airport/hangar";
    readonly '745': "Recreational airport";
    readonly '746': "Subway station";
    readonly '748': "Transit garage";
    readonly '749': "Public transportation - other";
    readonly '750': "Scientific, pharmaceutical, medical research facility (structures predominantly other than office)";
    readonly '755': "Lighthouses";
    readonly '760': "Military base or camp (CFB)";
    readonly '761': "Armoury";
    readonly '762': "Military education facility";
    readonly '805': "Post office or depot";
    readonly '806': "Postal mechanical sorting facility";
    readonly '810': "Fire Hall";
    readonly '812': "Ambulance Station";
    readonly '815': "Police Station";
    readonly '822': "Government - agricultural research facility";
    readonly '824': "Government - wharves and harbours";
    readonly '826': "Government - special educational facility";
    readonly '828': "Government - canals and locks";
    readonly '830': "Government - navigational facilities";
    readonly '832': "Government - historic site or monument";
    readonly '840': "Port authority - port activities";
    readonly '842': "Port authority - other activities";
};
export declare const serviceCodeNames: {
    readonly A: "All Services";
    readonly H: "Hydro Access";
    readonly M: "Municipal Water";
    readonly N: "No Services";
    readonly P: "Part Services";
    readonly S: "Sanitary Services";
    readonly T: "Septic System";
    readonly W: "Well Water";
    readonly X: "No Water";
    readonly Y: "No Water Disposal";
};
export declare const accessCodeNames: {
    readonly I: "Island Access";
    readonly L: "Land Locked";
    readonly N: "No Road Access";
    readonly O: "Private Road Access";
    readonly R: "Right-of-Way Access";
    readonly S: "Summer or Seasonal Access Only";
    readonly W: "Water Access Only";
    readonly Y: "Year Round Access by Road";
};
