export declare const unitClassDescriptions: {
    CA: string;
    CL: string;
    COM: string;
    ECL: string;
    EDN: string;
    EIL: string;
    FG: string;
    FL: string;
    FRU: string;
    IND: string;
    LF: string;
    LG: string;
    MF: string;
    ML: string;
    OE: string;
    OH: string;
    OT: string;
    PG: string;
    PGA: string;
    PU: string;
    RDU: string;
    REL: string;
    RU: string;
    RWY: string;
    TD: string;
    THE: string;
    TPL: string;
    UTC: string;
    VL: string;
};
export declare const realtyTaxClassNames: {
    A: string;
    C: string;
    D: string;
    E: string;
    F: string;
    G: string;
    H: string;
    I: string;
    J: string;
    K: string;
    L: string;
    M: string;
    N: string;
    O: string;
    P: string;
    Q: string;
    R: string;
    S: string;
    T: string;
    U: string;
    W: string;
    X: string;
    Y: string;
    Z: string;
};
export declare const realtyTaxQualifiers: Record<string, {
    class: string;
    name: string;
}>;
export declare const unitSupportNames: {
    P: string;
    S: string;
    A: string;
    C: string;
    D: string;
    B: string;
    N: string;
};
export declare const propertyTypeNames: {
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    0: string;
};
