export declare const unitClassDescriptions: {
    readonly CA: "Property vested in a Conservation Authority";
    readonly CL: "Conservation Land";
    readonly COM: "Commercial property used for business and subject to business assessment";
    readonly ECL: "An area of land in a commercial property that is excess to the operation of the business";
    readonly EDN: "Property occupied by an educational body";
    readonly EIL: "An area of land in a industrial property that is excess to the operation of the business";
    readonly FG: "Property other than vacant land and residential units occupied by the Federal Government Agencies, or owned and occupied by a foreign government as an embassy. This code is used when the unit is occupied by a tenant of the Federal Government";
    readonly FL: "Farmlands with or without farm outbuildings but doesn't include farmlands on which a farm residence exists";
    readonly FRU: "Farmlands on which a farm residence exists";
    readonly IND: "Industrial property used for business and subject to business assessment";
    readonly LF: "Landfill";
    readonly LG: "Property other than vacant land and occupied by municipal, regional or county levels of government. This code does not apply to public utilities, nor when the land is occupied by a tenant of the Local Government";
    readonly MF: "Properties or portions of properties for which the owner(s) have entered into an agreement with the Ministry of Natural Resources to have the land designated as Managed Forest";
    readonly ML: "Mining lands";
    readonly OE: "Certain specified charities and cemeteries that are not associated with a religious organization";
    readonly OH: "Property other than vacant land occupied by Ontario Hydro, but not when occupied by a tenant of Ontario Hydro";
    readonly OT: "Taxable properties for which a specific unit class code has not been developed. This code will include lands with improvements (boat houses, garages, sheds, etc.) that actually add value to the land; however, their use doesn't dictate a specific unit class code";
    readonly PG: "Property other than vacant land and residential units occupied by the Provincial Government, but not when occupied by a tenant of the Provincial Government";
    readonly PGA: "Property other than vacant land and residential units occupied by an agency of the Provincial Government, but not when occupied by a tenant of the Provincial Government Agency";
    readonly PU: "Property occupied by a public utility";
    readonly RDU: "Seasonal dwelling units";
    readonly REL: "Property used for religious purposes and cemeteries that are associated with a church";
    readonly RU: "Residential units";
    readonly RWY: "Railway property";
    readonly TD: "Property used for transportation or distribution";
    readonly THE: "Large theatres";
    readonly TPL: "Oil and gas transmissions pipelines";
    readonly UTC: "Utility transmission and distribution corridors";
    readonly VL: "Vacant lands other than farmland, mining land, conservation land, or those of a Conservation Authority. This includes land owned by the Federal Government, Provincial Governments, etc.";
};
export declare const realtyTaxClassNames: {
    readonly A: "Large Theatre";
    readonly C: "Commercial";
    readonly D: "Office Building";
    readonly E: "Exempt";
    readonly F: "Farm";
    readonly G: "Parking Lot";
    readonly H: "Landfill";
    readonly I: "Industrial";
    readonly J: "Industrial (New Construction)";
    readonly K: "Large Industrial (New Construction)";
    readonly L: "Large Industrial";
    readonly M: "Multi-Residential";
    readonly N: "New Multi-Residential";
    readonly O: "Resort Condominium";
    readonly P: "Pipeline";
    readonly Q: "Professional Sports Facility";
    readonly R: "Residential";
    readonly S: "Shopping Centre";
    readonly T: "Managed Forests";
    readonly U: "Utility Transmission and Distribution Corridors";
    readonly W: "Railway Right-of-Way";
    readonly X: "Commercial (New Construction)";
    readonly Y: "Office Building (New Construction)";
    readonly Z: "Shopping Centre (New Construction)";
};
export declare const realtyTaxQualifiers: Readonly<Record<string, {
    class: 'Payment in Lieu' | 'Taxable';
    name: string;
}>>;
export declare const unitSupportNames: {
    readonly A: "French-Public";
    readonly B: "Split";
    readonly C: "French-Separate";
    readonly D: "Protestant-Separate";
    readonly N: "No Support";
    readonly P: "English-Public";
    readonly S: "English-Separate";
};
export declare const propertyTypeNames: {
    readonly '0': "Rights-of-Way";
    readonly '1': "Residential";
    readonly '2': "Multi-Residential";
    readonly '3': "Commercial";
    readonly '4': "Industrial";
    readonly '5': "Pipeline";
    readonly '6': "Farm";
    readonly '7': "Recreational";
    readonly '8': "Residential Condos";
    readonly '9': "Other/Unique Properties";
};
