name: Coverage Testing

on: [workflow_dispatch, push, pull_request]

permissions: read-all

jobs:
  Coverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [ 18, 20, 22, 24 ]
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}

      - name: Install Application
        run: |
          npm ci
          npm install -g c8

      - name: Run Coverage Testing
        run: c8 --reporter=lcov --reporter=text --reporter=text-summary node --test

      - name: Codecov
        if: ${{ github.event_name != 'pull_request' && env.CODECOV_TOKEN != '' && matrix.node == 16 }}
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov -t ${CODECOV_TOKEN}